/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedFundRouteImport } from './routes/_authenticated/fund'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as AuthenticatedServicesExamPinRouteImport } from './routes/_authenticated/services/exam-pin'
import { Route as AuthenticatedServicesElectricityRouteImport } from './routes/_authenticated/services/electricity'
import { Route as AuthenticatedServicesDataRouteImport } from './routes/_authenticated/services/data'
import { Route as AuthenticatedServicesCableRouteImport } from './routes/_authenticated/services/cable'
import { Route as AuthenticatedServicesBettingRouteImport } from './routes/_authenticated/services/betting'
import { Route as AuthenticatedServicesAirtimeRouteImport } from './routes/_authenticated/services/airtime'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin/banners'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFundRoute = AuthenticatedFundRouteImport.update({
  id: '/fund',
  path: '/fund',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedServicesExamPinRoute =
  AuthenticatedServicesExamPinRouteImport.update({
    id: '/services/exam-pin',
    path: '/services/exam-pin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServicesElectricityRoute =
  AuthenticatedServicesElectricityRouteImport.update({
    id: '/services/electricity',
    path: '/services/electricity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServicesDataRoute =
  AuthenticatedServicesDataRouteImport.update({
    id: '/services/data',
    path: '/services/data',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServicesCableRoute =
  AuthenticatedServicesCableRouteImport.update({
    id: '/services/cable',
    path: '/services/cable',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServicesBettingRoute =
  AuthenticatedServicesBettingRouteImport.update({
    id: '/services/betting',
    path: '/services/betting',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServicesAirtimeRoute =
  AuthenticatedServicesAirtimeRouteImport.update({
    id: '/services/airtime',
    path: '/services/airtime',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/admin/banners',
    path: '/admin/banners',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/about': typeof AuthenticatedAboutRoute
  '/fund': typeof AuthenticatedFundRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/services/airtime': typeof AuthenticatedServicesAirtimeRoute
  '/services/betting': typeof AuthenticatedServicesBettingRoute
  '/services/cable': typeof AuthenticatedServicesCableRoute
  '/services/data': typeof AuthenticatedServicesDataRoute
  '/services/electricity': typeof AuthenticatedServicesElectricityRoute
  '/services/exam-pin': typeof AuthenticatedServicesExamPinRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/about': typeof AuthenticatedAboutRoute
  '/fund': typeof AuthenticatedFundRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/services/airtime': typeof AuthenticatedServicesAirtimeRoute
  '/services/betting': typeof AuthenticatedServicesBettingRoute
  '/services/cable': typeof AuthenticatedServicesCableRoute
  '/services/data': typeof AuthenticatedServicesDataRoute
  '/services/electricity': typeof AuthenticatedServicesElectricityRoute
  '/services/exam-pin': typeof AuthenticatedServicesExamPinRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/fund': typeof AuthenticatedFundRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/services/airtime': typeof AuthenticatedServicesAirtimeRoute
  '/_authenticated/services/betting': typeof AuthenticatedServicesBettingRoute
  '/_authenticated/services/cable': typeof AuthenticatedServicesCableRoute
  '/_authenticated/services/data': typeof AuthenticatedServicesDataRoute
  '/_authenticated/services/electricity': typeof AuthenticatedServicesElectricityRoute
  '/_authenticated/services/exam-pin': typeof AuthenticatedServicesExamPinRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/about'
    | '/fund'
    | '/history'
    | '/home'
    | '/profile'
    | '/referrals'
    | '/settings'
    | '/admin/banners'
    | '/services/airtime'
    | '/services/betting'
    | '/services/cable'
    | '/services/data'
    | '/services/electricity'
    | '/services/exam-pin'
    | '/api/public/paystack-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/about'
    | '/fund'
    | '/history'
    | '/home'
    | '/profile'
    | '/referrals'
    | '/settings'
    | '/admin/banners'
    | '/services/airtime'
    | '/services/betting'
    | '/services/cable'
    | '/services/data'
    | '/services/electricity'
    | '/services/exam-pin'
    | '/api/public/paystack-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/about'
    | '/_authenticated/fund'
    | '/_authenticated/history'
    | '/_authenticated/home'
    | '/_authenticated/profile'
    | '/_authenticated/referrals'
    | '/_authenticated/settings'
    | '/_authenticated/admin/banners'
    | '/_authenticated/services/airtime'
    | '/_authenticated/services/betting'
    | '/_authenticated/services/cable'
    | '/_authenticated/services/data'
    | '/_authenticated/services/electricity'
    | '/_authenticated/services/exam-pin'
    | '/api/public/paystack-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fund': {
      id: '/_authenticated/fund'
      path: '/fund'
      fullPath: '/fund'
      preLoaderRoute: typeof AuthenticatedFundRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/services/exam-pin': {
      id: '/_authenticated/services/exam-pin'
      path: '/services/exam-pin'
      fullPath: '/services/exam-pin'
      preLoaderRoute: typeof AuthenticatedServicesExamPinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services/electricity': {
      id: '/_authenticated/services/electricity'
      path: '/services/electricity'
      fullPath: '/services/electricity'
      preLoaderRoute: typeof AuthenticatedServicesElectricityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services/data': {
      id: '/_authenticated/services/data'
      path: '/services/data'
      fullPath: '/services/data'
      preLoaderRoute: typeof AuthenticatedServicesDataRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services/cable': {
      id: '/_authenticated/services/cable'
      path: '/services/cable'
      fullPath: '/services/cable'
      preLoaderRoute: typeof AuthenticatedServicesCableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services/betting': {
      id: '/_authenticated/services/betting'
      path: '/services/betting'
      fullPath: '/services/betting'
      preLoaderRoute: typeof AuthenticatedServicesBettingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services/airtime': {
      id: '/_authenticated/services/airtime'
      path: '/services/airtime'
      fullPath: '/services/airtime'
      preLoaderRoute: typeof AuthenticatedServicesAirtimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/admin/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedFundRoute: typeof AuthenticatedFundRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedServicesAirtimeRoute: typeof AuthenticatedServicesAirtimeRoute
  AuthenticatedServicesBettingRoute: typeof AuthenticatedServicesBettingRoute
  AuthenticatedServicesCableRoute: typeof AuthenticatedServicesCableRoute
  AuthenticatedServicesDataRoute: typeof AuthenticatedServicesDataRoute
  AuthenticatedServicesElectricityRoute: typeof AuthenticatedServicesElectricityRoute
  AuthenticatedServicesExamPinRoute: typeof AuthenticatedServicesExamPinRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedFundRoute: AuthenticatedFundRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
  AuthenticatedServicesAirtimeRoute: AuthenticatedServicesAirtimeRoute,
  AuthenticatedServicesBettingRoute: AuthenticatedServicesBettingRoute,
  AuthenticatedServicesCableRoute: AuthenticatedServicesCableRoute,
  AuthenticatedServicesDataRoute: AuthenticatedServicesDataRoute,
  AuthenticatedServicesElectricityRoute: AuthenticatedServicesElectricityRoute,
  AuthenticatedServicesExamPinRoute: AuthenticatedServicesExamPinRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
